add subtitles module
OngDev/course-manager pull request #39
Opened 2021-05-05 03:09 UTC by jorodragon

2021-05-05 06:34 UTC, MiloNguyen95 commented on packages/server/src/modules/subtitles/entities/subtitle.entity.ts
> +export class Subtitle {
Kế thừa thằng Base Entity đi em

2021-05-05 06:36 UTC, MiloNguyen95 commented on packages/server/src/modules/subtitles/subtitles.decorator.ts
> +export function SubtitleSwagger() {
Ủa đống này có cần thiết ko e, a nghĩ nó tự bắt xong tự add vào swagger chứ nhỉ

2021-05-05 06:37 UTC, MiloNguyen95 commented on packages/server/src/modules/subtitles/subtitles.decorator.ts
> +export function SubtitleSwagger() {
Hay là phải khai báo như này mới có thêm đống info về exception?

2021-05-05 06:39 UTC, MiloNguyen95 requested changes
Sửa warning eslint, và giải thích các class swagger decorators

2021-05-05 07:04 UTC, jorodragon commented on packages/server/src/modules/subtitles/entities/subtitle.entity.ts
> +export class Subtitle {
vâng anh, em sửa r đó ạ

2021-05-05 07:06 UTC, jorodragon commented on packages/server/src/modules/subtitles/subtitles.decorator.ts
> +export function SubtitleSwagger() {
vâng, k cần cái swagger decorator này cũng đc ạ, em xóa r ạ

2021-05-07 14:34 UTC, MiloNguyen95 approved these changes

2021-05-07 16:20 UTC, MiloNguyen95 approved these changes

2021-05-07 16:20 UTC, merged